# Use an official Golang runtime as the base image
FROM golang:1.23.5 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Copy the rest of the application code
COPY . .

# Set the working directory inside the container
WORKDIR /app

# Expose the port the application will run on
EXPOSE 8080

# Command to run the application
CMD ["go","run","."]